using System;
using System.ComponentModel;
using Xafari.FW.ExpressApp;
using Xafari.FW.ExpressApp.Security.Strategy;

namespace Project.Win
{
    /// <summary>
    /// Class SmetaWinModule. This class cannot be inherited.
    /// </summary>
    [ToolboxItemFilter("Xaf.Platform.Win")]
    public sealed partial class ProjectWinModule : ModuleBase
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProjectWinModule"/> class.
        /// </summary>
        /// <autogeneratedoc />
        public ProjectWinModule()
        {
            InitializeComponent();
        }
    }
}
