// Autogenerated file
using System.Reflection;
using Xafari.SmartDesign;

[assembly: SmartDesignStrategy(typeof(XafariSmartDesignStrategy))]
#pragma warning disable 0436
#if SKIPPRODUCTINFO
#else
[assembly: AssemblyProduct(ProductInfo.AssemblyProduct)]
[assembly: AssemblyCopyright(ProductInfo.AssemblyCopyright)]
[assembly: AssemblyTrademark(ProductInfo.AssemblyTrademark)]
[assembly: AssemblyCompany(ProductInfo.AssemblyCompany)]
[assembly: AssemblyVersion(ProductInfo.AssemblyVersion)]
[assembly: AssemblyFileVersion(ProductInfo.AssemblyFileVersion)]
#endif

partial class ProductInfo
{
	public const string AssemblyProduct = "Project";
	public const string AssemblyCopyright = "Company 2024";
	public const string AssemblyTrademark = "Company";
	public const string AssemblyCompany = "Company";
#if DEBUG
    public const string AssemblyFileVersion = "1.0.0.2";
	public const string AssemblyVersion = AssemblyFileVersion;
	public const string MajorMinorVersion = "1.1";
    public const string SpecificBuildNumber = "0";
#else
    public const string AssemblyFileVersion = "1.0.0.0";
    public const string AssemblyVersion = AssemblyFileVersion;
    public const string MajorMinorVersion = "1.1";
    public const string SpecificBuildNumber = "0";
#endif
}
#pragma warning restore 0436
