using System;
using Xafari.FW.ExpressApp;
using Xafari.FW.ExpressApp.Updating;
using Xafari.FW.Xpo;

namespace Promject.Presentation.Blazor
{
    /// <summary>
    /// Class Updater.
    /// </summary>
    public class Updater : ModuleUpdater
    {
        /// <summary>
        /// Initializes a new instance of the ModuleUpdater.
        /// </summary>
        /// <param name="objectSpace">An <see cref="T:Xafari.FW.ExpressApp.IObjectSpace" /> object which represents the Object Space used to update the database. This parameter's value is assigned to the protected <b>ObjectSpace</b> property.</param>
        /// <param name="currentDBVersion">A <see cref="T:System.Version" /> object which represents the current database version. This parameter's value is assigned to the protected <b>CurrentDBVersion</b> property.</param>
        /// <autogeneratedoc />
        public Updater(IObjectSpace objectSpace, Version currentDBVersion) : base(objectSpace, currentDBVersion) { }
        /// <summary>
        /// Performs a database update after the database schema is updated.
        /// </summary>
        /// <autogeneratedoc />
        public override void UpdateDatabaseAfterUpdateSchema()
        {
            base.UpdateDatabaseAfterUpdateSchema();
        }
    }
}
